using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace Services.Helpers
{
    public class SendEmail
    {
        public void SendMail2Step(string SMTPServer, int SMTP_Port, string From, string Password, string To, string Subject, string Body, string[] FileNames)
        {
            var smtpClient = new SmtpClient(SMTPServer, SMTP_Port)
            {
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                EnableSsl = true
            };
            smtpClient.Credentials = new NetworkCredential(From, Password); //Use the new password, generated from google!
            var message = new System.Net.Mail.MailMessage(new System.Net.Mail.MailAddress(From, "ResetPassword"), new System.Net.Mail.MailAddress(To, To));
            message.Subject = Subject;
            message.Body = Body;
            smtpClient.Send(message);
        }

        public static void Send(string To, string Subject, string Body)
        {
            var sendEmail = new SendEmail();
            sendEmail.SendMail2Step("smtp.gmail.com", 587, "chauanhtuan04@gmail.com",
                "bvrf nzed slxg cypy",//This will be generated by google, copy it here.
                To, Subject, Body, null);
        }
    }
}